name: Sync upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge upstream
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add upstream https://github.com/icloud-photos-downloader/icloud_photos_downloader.git
          git fetch upstream master
          git merge --no-edit upstream/master
          git push origin master
